### ISSUE TITLE
prettierrc 설정 2개 존재합니다.

### ISSUE THREAD

**Issue by jonathan-onuii** [GoodOnuii/next#25]
**Describe the bug**
1개로 통일되어야 할 것 같습니다.
![스크린샷 2023-03-03 오후 5 24 32](https://user-images.githubusercontent.com/118155422/222669492-d3ff354a-f91d-4b77-98f5-62f5af38ab90.png)

**Comment by vivi-onuii** [comment]
@jonathan-onuii PR 올려주시겠어요?!

**Comment by vivi-onuii** [comment]
@jonathan-onuii FYI 로, 설정은 @seoltab/eslint-config-web 와 동일하게 가져갑니다.

**Comment by jonathan-onuii** [comment]
@vivi-onuii 제가 설정을 좀 봤는데, @seoltab/eslint-config-web가 해당 레포에 설치가 안되어 있습니다. 혹시 해당 작업 관련해서 제가 고쳐서 올려도 될까요?

**Comment by vivi-onuii** [comment]
@jonathan-onuii 아... 맞아요. [이녀석](https://github.com/GoodOnuii/next/issues/26) 이랑 같이 수정하려고 했는데 그러면 부탁드릴게요! 기존 GoodOnuii 는 제거해 주시고, @seoltab/eslint-config-web 로 교체 PR 올려주시면 제가 리뷰 후 main 까지 한번에 가져갈게요. 감삼다 > <
